# Generated by Django 3.1.1 on 2020-10-06 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacionamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro', models.IntegerField()),
                ('zona', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Estacionamientos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Experiencias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('direccion', models.CharField(blank=True, max_length=150)),
                ('salario', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('especialidad', models.PositiveSmallIntegerField(choices=[(1, 'Pediatria'), (2, 'Medicina General'), (3, 'Estetica')])),
                ('foto', models.ImageField(blank=True, default='medicos/sinfoto.jpg', null=True, upload_to='medicos/img/')),
                ('estacionamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estacionamiento')),
                ('experiencia', models.ManyToManyField(blank=True, null=True, to='core.Experiencia')),
            ],
            options={
                'verbose_name_plural': 'Medicos',
                'ordering': ['id'],
            },
        ),
    ]
